apiVersion: v2
name: city-population-api
description: A Helm chart for City Population API with Elasticsearch
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - api
  - elasticsearch
  - population
maintainers:
  - name: SRE Team
    email: sre@example.com
dependencies:
  - name: elasticsearch
    version: "7.17.3"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
